### ISSUE TITLE
No payload provided for resolve 

### ISSUE THREAD

**Issue by theKashey** [afitiskin/redux-saga-routines#4]
Just wondering why?
```javascript
if (success) {
    yield call(resolve); <-- ,getPayload(success); 
  } else {
    yield call(reject, getPayload(failure));
  }
```

**Comment by afitiskin** [comment]
Promises has been designed to use with `redux-form` and there is a strange behaviour of `redux-form` async validation: https://github.com/erikras/redux-form/issues/2056. So I decided to resolve promise without any payload to be sure it will be treated correctly

**Comment by theKashey** [comment]
As long this is problem of redux form, and yours project is not just redux-form related thing (it is just awesome by its own) - it is not a good idea to break something inside it to fit others project API details.
There is no difference how one will fulfill redux-form promise - via standard promise or via saga. It is up to user to fulfill it `properly`. Not to you.
Be more transparent. IMHO.

**Comment by afitiskin** [comment]
@theKashey I see no reason to use promises without `redux-form` (they will be added just to support form validation and submit). Could you please provide any example where you use promises and success payload?

**Comment by theKashey** [comment]
Your library called redux-saga-routines, not redux-form-saga-routines. 
In mine case I just want to have a promise from an action, and next await for it. 
For example - on form submit I want to dispatch an action, which will trigger saga to perform network request and await for completion. Or display modal dialog, and yet again await for completion.
Your library is very useful if one want to observe some dispatchable action using promises. Or just await for some sequence in a simple way.

**Comment by afitiskin** [comment]
@theKashey I'd like to see code example :)

**Comment by theKashey** [comment]
```javascript
onAction(){
  this.prop.showEnterYourNameModalDialog() <-- will trigger saga
     .then(name => this.props.continueWithName(name)) --> will return name entered in modal dialog
     .catch(shutDown) <-- handle reject.
}
```

**Comment by afitiskin** [comment]
You splitted your logic into 2 parts: one part – in saga, another one – in component. This is a wrong way bacause all your logic should be placed in your saga. How you can improve your code:

1. In your component you only render your state and only trigger actions.
2. In your saga you handle triggered actions and do all of your side effects.

So, in component you only trigger your acation:
```javascript
onAction() {
  this.prop.showEnterYourNameModalDialog.trigger();
}
```

All side effects and logick should be placed in your saga and all your state should be changed in reducers and stored in store.

E.g. on `showEnterYourNameModalDialog.TRIGGER` you change `nameDialog.visible` to `true` (by reducer).
Then, `EnterYourNameModalDialog` component can dispatch 2 actions: `showEnterYourNameModalDialog.SUCCESS` (when user enters the name and clicks submit) or `showEnterYourNameModalDialog.FAILURE` (when user clicks cancel). Both actions should be taken in your saga and in case of `SUCCESS` should be triggered new saga `continueWithName`, in other case (`FAILURE`) – `shutDown` saga.
Also, you can dispatch `showEnterYourNameModalDialog.FULFILL` in both cases to notify other components that `EnterYourNameModalDialog` has been closed.

So, my point is: all your logic should be in your sagas, all state should be in your store, and components are only for render & trigger.
That's why you don't need to use promises from this package directly.

**Comment by theKashey** [comment]
Dont be so idealistic – not everything must be solved via global store, events and sagas. 
I can agree that it is good to have _all_ logic inside sagas, but it is not very usable.
Just imagine - some deep component opens modal dialog, and awaits result from it. What is better - to add 100500 different stores to keep temporary variable, and twice more to control visible form of components.. or just have promise-based communication channel?
Literally you should not store in store something that should be stored at store.
So you library just exists to solve tasks like this. I hope you know better – why.

**Comment by afitiskin** [comment]
Ok, it's your chose how to do your job.
My opinion how to solve the issue:
1. Due to #2 change default action to trigger (instead of promise)
2. Due to #2 add new routine method `.form()` that will work as default action at the moment (fully compatible with `redux-form`)
3. Add new routine method `promise()` that will work similar to `.form` but with providing payload for  resolve.

Later, when `redux-form` will fix their issue `.form()` will be just alias to `.promise()`
What do you think?

**Comment by theKashey** [comment]
Like a
```javascript
routine.form = (data, dispatch) => {
  return new Promise((resolve, reject) => dispatch({
    type: PROMISE_ACTION,
    payload: {
      data,
      params: routineParams,
      defer: { () => resolve, reject }, // drop payload
    },
  }));
};
```
Yes, it will work. But whole routine is created by PROMISE_ACTION and how #2 will work by itself - I cant imagine.
And for me it is better to add new action creator to submit a redux form, and, if one provided payload to that action,- throw a warning to console with issue link.
The best way to fix redux-form issue - do not provide payload by yourself, not to drop it.

**Comment by afitiskin** [comment]
@theKashey please take a look at `next` branch.  I fixed all 3 points listed above:
1. You can change default action by passing it's name as 3rd parameter to `createRoutine`:
    ```javascript
    const triggerByDefault = createRoutine('PREFIX', i => i, 'trigger');
    triggerByDefault === triggerByDefault.trigger;
    ```
2. `.form()` method has been added, promise resolved without any payload (for compatibility with `redux-form`)
3. `.promise()` method has been added, promise resolved with payload, as you ask in this issue.

**Comment by theKashey** [comment]
Good job comrade 👍
