### ISSUE TITLE
Can redux-saga-routines work with redux compose?

### ISSUE THREAD

**Issue by Ctsavas** [afitiskin/redux-saga-routines#54]
Hello,

I've tried making it work with redux-saga-routines and compose instead of using sagaMiddleware.run. Should that be working?

**Comment by afitiskin** [comment]
`compose` is just an utility function to make function composition, so i'm not sure what you are trying to do.
`createRoutine` may work without `redux-saga`, since it's just a creator, but handling promises is not possible without `routinePromiseWatcherSaga` which is designed to work with `redux-saga`, so it will not work without it.

**Comment by afitiskin** [comment]
@Ctsavas do you still need help with it?

**Comment by Ctsavas** [comment]
Hello @afitiskin , sorry for the delayed response.

I was trying to use `redux-saga-routines` with loading `routinePromiseWatcherSaga` using the `injectSaga` pattern on the component level (as described here for example https://heygrady.github.io/redux-saga-watch-actions/docs/middleware/injectSaga.html). 
I solved my problem by adding `routinePromiseWatcherSaga` to a top parent component.
My problem with asking for help in the first place was that the suggested docs way of loading the saga saga with `sagaMiddleware.run()`, which I couldn't use in my case.

**Comment by afitiskin** [comment]
If you check the source code of `injectSaga` you will see that `injectSaga` uses `sagaMiddleware.run`, so it will work for you
