### ISSUE TITLE
How to bind routines?

### ISSUE THREAD

**Issue by alexpanchuk** [afitiskin/redux-saga-routines#55]
Where is bindRoutineCreators? Is there other way to bind routines?

**Comment by afitiskin** [comment]
Usually, it is enough to bind only `trigger` function, since action triggered in the component and all other steps are made in sagas:

```
const mapStateToProps = (state) => ({});

const mapDispatchToProps = {
  load: loadSomethingRoutine.trigger,
};

class MyComponent extends Component {
  componentDidMount() {
    this.props.load(); // triggers load action, that will be handled in saga
  }

  render() {
    return null;
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(MyComponent);
```

It is very rare case, when you really need in your component all 5 action creators bound to the store, so just bind that you are really need like in example above.

If you are going to use routine with `redux-form` there is special `bindRoutineToReduxForm` method.

**Comment by alexpanchuk** [comment]
Thank you
