### ISSUE TITLE
Question: Is using bindRoutineCreators required?

### ISSUE THREAD

**Issue by wasinsandiego** [afitiskin/redux-saga-routines#7]
Just curious, will `bindRoutineCreators` give us something more than if we just let `react-redux` wrap our action creators in a dispatcher for us.

In other words, what are the caveats of doing this?
```javascript
const mapDispatchToProps = {
  fetchData
}
```

Instead of this?
```javascript
const mapDispatchToProps = (dispatch) => {
  return {
    ...bindRoutineCreators({ fetchData }, dispatch)
  }
}
```

**Comment by afitiskin** [comment]
Routine is a bit different of simple action creators, so it is not working with `bindActionCreators` (that is applied by `react-redux` in case of object value for `mapDispatchToProps`).  I will try to describe the difference between them.

Due to compatibility with `redux-form` routine has specific signature: 
```
(payload, dispatch) => Promise
``` 

Simple action creator has another signature: 
```
(payload) => Object
```

What `bindActionCreator` actually does? It just wraps our action creator into `dispatch`: 
```
bindActionCreator = (actionCreator, dispatch) => (...args) => dispatch(actionCreator(...args));
```

So, if we apply `bindActionCreator` on routine we will send to `dispatch` Promise instead of plain action object, so it won't work correctly. Also, `bindActionCreator` only wraps the function itself, but the routine has actually 5 functions, so they will not be bound to dispatch.

That's why using of `bindRoutineCreators` are necessary. First of all, it properly bind main routine function to `dispatch` and also bind each of 5 other routine's functions. So, after applying `bindRotuineCreators` you are allowed to use it as you want without thinking of `dispatch` at all.

**Comment by wasinsandiego** [comment]
Great utility! Thanks for the prompt reply; It makes total sense.

I ended up doing this since I have been letting `connect` do the dispatch wrapping on it's own for me. Seems to be working.
```javascript
const mapDispatchToProps = {
  fetchTrigger: fetchRoutine.trigger
}
```

When we use your routines for `redux-form` we'll use the `bindRoutineCreators` utility. I think it will help distinguish those routines that are used for `redux-form` and those that aren't.

BTW, I really like how the `redux-saga-routines` are working out so far. Thanks!

**Comment by afitiskin** [comment]
You are doing it right! Since I used to use `redux-saga-routines` in many various cases I found that it is really good to separate form routines and make plain routine as simple as possible. So I will spend some time to do that. Will let you know about updates.
